name: AP Testing Calendar
#! change this to a cron job
on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: "node:16"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GITHUB Actions
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Install Dependencies
        run: npm install
      - name: Run Code
        env:
          SHEETS_ID: ${{secrets.SHEETS_ID}}
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
          AP_API_KEY: ${{secrets.AP_API_KEY}}
          GOOGLE_OAUTH_CLIENT_ID: ${{secrets.GOOGLE_OAUTH_CLIENT_ID}}
          GOOGLE_OAUTH_CONSUMER_SECRET: ${{secrets.GOOGLE_OAUTH_CONSUMER_SECRET}}
          GOOGLE_REFRESH_TOKEN: ${{secrets.GOOGLE_REFRESH_TOKEN}}
          GOOGLE_ACCESS_TOKEN: ${{secrets.GOOGLE_ACCESS_TOKEN}}
        run: node elex-testing-results/index.js
