name: AP Tabulation and Race Call Statuses

on: push
    
jobs:
  runEndpoint:
    runs-on: ubuntu-latest
    container: "node:16"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run Code
        env:
          SHEETS_ID: ${{secrets.SHEETS_ID}}
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
        run: node elex-tabulation-data/main.js

  job2:
      runs-on: ubuntu-latest
      # needs: runEndpoint 
      # if: if ${{ ${{needs.runEndpoint}} == TRUE }}
      container: "node:16"
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Install Dependencies
          run: npm install
        - name: Run Code
          env:
            SHEETS_ID: ${{secrets.SHEETS_ID}}
            SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
            AP_API_KEY: ${{secrets.AP_API_KEY}}
            GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
          run: echo ${{needs.runEndpoint}}
          # run: node elex-tabulation-data/index.js
