name: AP Tabulation and Race Call Statuses

on: push
    
jobs:
  runEndpoint:
    runs-on: ubuntu-latest
    container: "node:16"
    outputs:
      output1: ${{ steps.step1.outputs.bool }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run Code
        id: step1
        env:
          SHEETS_ID: ${{secrets.SHEETS_ID}}
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
        run: |
          shouldRunEndpoint=$(node elex-tabulation-data/main.js)
          echo $shouldRunEndpoint
          echo "bool=$shouldRunEndpoint" >> $GITHUB_OUTPUT

# Do I hve to checkout and install again?
  job2:
      runs-on: ubuntu-latest
      needs: runEndpoint 
      # if: if ${{ ${{needs.runEndpoint}} == TRUE }}
      container: "node:16"
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Install Dependencies
          run: npm install
        - name: Run Code
          env:
            SHEETS_ID: ${{secrets.SHEETS_ID}}
            SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
            AP_API_KEY: ${{secrets.AP_API_KEY}}
            GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
          run: echo ${{needs.runEndpoint.outputs.output1}}
          # run: node elex-tabulation-data/index.js
