name: AP Tabulation and Race Call Statuses

on:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  job2:
    runs-on: ubuntu-latest
    container: "node:20"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run Code
        env:
          SHEETS_ID: ${{secrets.SHEETS_ID}}
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
          AP_API_KEY: ${{secrets.AP_API_KEY}}
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
        run: |
          # echo ${{needs.runEndpoint.outputs.output1}}
          node elex-tabulation-data/index.js
